import Banner from "../../assets/fb.png";

export const AboutUs = () => {
  return (
    <>
      ABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US
      PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT
      US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US
      PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT
      US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US
      PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT
      US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US
      PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT
      US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US
      PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT
      US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US
      PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT
      US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US
      PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT
      US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGEABOUT US PAGE
    </>
  );
};
